# This workflow will build and test the .NET project for better validation
name: Build & Test

on:
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TDDFizzBuzz/TDDFizzBuzz.csproj
    - name: Build
      run: dotnet build TDDFizzBuzz/TDDFizzBuzz.csproj --no-restore
    - name: Test
      run: dotnet test TDDFizzBuzz.Tests/TDDFizzBuzz.Tests.csproj --no-build --verbosity normal
